export enum UserManagementActionTypes {
    USER_LIST_WITH_FILTER = '@@userManagement/USER_LIST_WITH_FILTER',
    USER_LIST_WITH_FILTER_SUCCESS = '@@userManagement/USER_LIST_WITH_FILTER_SUCCESS',
    USER_LIST_WITH_FILTER_ERROR = '@@userManagement/USER_LIST_WITH_FILTER_ERROR',

    USER_UPDATE_STATUS = '@@userManagement/USER_UPDATE_STATUS',
    USER_UPDATE_STATUS_SUCCESS = '@@userManagement/USER_UPDATE_STATUS_SUCCESS',
    USER_UPDATE_STATUS_ERROR = '@@userManagement/USER_UPDATE_STATUS_ERROR',

    USER_DELETE = '@@userManagement/USER_DELETE',
    USER_DELETE_SUCCESS = '@@userManagement/USER_DELETE_SUCCESS',
    USER_DELETE_ERROR = '@@userManagement/USER_DELETE_ERROR',
}
