export enum RolesAndRightsActionTypes {
    PERMISSION_MODULE_LIST = '@@roles/PERMISSION_MODULE_LIST',
    PERMISSION_MODULE_LIST_SUCCESS = '@@roles/PERMISSION_MODULE_LIST_SUCCESS',
    PERMISSION_MODULE_LIST_ERROR = '@@roles/PERMISSION_MODULE_LIST_ERROR',

    PERMISSION_MODULE_ADD = '@@roles/PERMISSION_MODULE_ADD',
    PERMISSION_MODULE_ADD_SUCCESS = '@@roles/PERMISSION_MODULE_ADD_SUCCESS',
    PERMISSION_MODULE_ADD_ERROR = '@@roles/PERMISSION_MODULE_ADD_ERROR',

    PERMISSION_MODULE_DELETE = '@@roles/PERMISSION_MODULE_DELETE',
    PERMISSION_MODULE_DELETE_SUCCESS = '@@roles/PERMISSION_MODULE_DELETE_SUCCESS',
    PERMISSION_MODULE_DELETE_ERROR = '@@roles/PERMISSION_MODULE_DELETE_ERROR',

    PERMISSION_LIST = '@@roles/PERMISSION_LIST',
    PERMISSION_LIST_SUCCESS = '@@roles/PERMISSION_LIST_SUCCESS',
    PERMISSION_LIST_ERROR = '@@roles/PERMISSION_LIST_ERROR',

    PERMISSION_ADD = '@@roles/PERMISSION_ADD',
    PERMISSION_ADD_SUCCESS = '@@roles/PERMISSION_ADD_SUCCESS',
    PERMISSION_ADD_ERROR = '@@roles/PERMISSION_ADD_ERROR',

    PERMISSION_DELETE = '@@roles/PERMISSION_DELETE',
    PERMISSION_DELETE_SUCCESS = '@@roles/PERMISSION_DELETE_SUCCESS',
    PERMISSION_DELETE_ERROR = '@@roles/PERMISSION_DELETE_ERROR',

    PERMISSION_ASSIGN = '@@roles/PERMISSION_ASSIGN',
    PERMISSION_ASSIGN_SUCCESS = '@@roles/PERMISSION_ASSIGN_SUCCESS',
    PERMISSION_ASSIGN_ERROR = '@@roles/PERMISSION_ASSIGN_ERROR',

}