export enum SubAdminUserActionTypes {
    SET_ADMIN_USER_ID = '@@subAdminUsers/SET_ADMIN_USER_ID',

    ADMIN_USERS_LIST = '@@subAdminUsers/ADMIN_USERS_LIST',
    ADMIN_USERS_LIST_SUCCESS = '@@subAdminUsers/ADMIN_USERS_LIST_SUCCESS',
    ADMIN_USERS_LIST_ERROR = '@@subAdminUsers/ADMIN_USERS_LIST_ERROR',

    ADMIN_USERS_ADD = '@@subAdminUsers/ADMIN_USERS_ADD',
    ADMIN_USERS_ADD_SUCCESS = '@@subAdminUsers/ADMIN_USERS_ADD_SUCCESS',
    ADMIN_USERS_ADD_ERROR = '@@subAdminUsers/ADMIN_USERS_ADD_ERROR',

    ADMIN_USERS_DELETE = '@@subAdminUsers/ADMIN_USERS_DELETE',
    ADMIN_USERS_DELETE_SUCCESS = '@@subAdminUsers/ADMIN_USERS_DELETE_SUCCESS',
    ADMIN_USERS_DELETE_ERROR = '@@subAdminUsers/ADMIN_USERS_DELETE_ERROR',

    ADMIN_USERS_EDIT = '@@subAdminUsers/ADMIN_USERS_EDIT',
    ADMIN_USERS_EDIT_SUCCESS = '@@subAdminUsers/ADMIN_USERS_EDIT_SUCCESS',
    ADMIN_USERS_EDIT_ERROR = '@@subAdminUsers/ADMIN_USERS_EDIT_ERROR',

    UPDATE_ADMIN_STATUS = '@@subAdminUsers/UPDATE_ADMIN_STATUS',
    UPDATE_ADMIN_STATUS_SUCCESS = '@@subAdminUsers/UPDATE_ADMIN_STATUS_SUCCESS',
    UPDATE_ADMIN_STATUS_ERROR = '@@subAdminUsers/UPDATE_ADMIN_STATUS_ERROR',
}
